### ISSUE TITLE
Launching application with Bluetooth disabled and using Auto Drive or Manual mode. 

### ISSUE THREAD

**Issue by ghost** [sesstigit/Android-Car-duino#7]
#### Issue description

Launching the mobile application with the device's Bluetooth turned off and attempting to use Auto Drive or Manual mode will cause the application to crash. 

#### Steps to reproduce the issue

1.  Turn off device's Bluetooth
2.  Launch CARdunio app
3. Select Auto Drive or Manual then selecting a direction

#### What's the expected result?

- Application should warn, on launch, that Bluetooth connectivity is off, and disallow actions that require Bluetooth. 

#### What's the actual result?

- Upon following the reproduction steps the application crash. 

#### Additional details / screenshot

-

**Comment by DataQub3** [comment]
OK.  That needs fixing.   I will take a look at the code.

**Comment by DataQub3** [comment]
Bug is now fixed for "Manual" mode (both Joystick and Basic manual).  An error message is displayed to the screen saying to enable bluetooth.
Bug is also fixed for "Auto Drive" mode.  It no longer crashes, but there is no error message about bluetooth because the screen is in camera mode.  I figure if Auto Drive does not work, a user will then try Manual and get the error message.
