### ISSUE TITLE
Replace Manual mode with joystick-style control

### ISSUE THREAD

**Issue by ghost** [sesstigit/Android-Car-duino#9]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

* **What is the current behavior?**

Currently you control the car via buttons, this control style may be less intuitive to people who don't understand the meaning of '++'. It's also harder to handle with.

* **Related code**
```
Android-Car-duino/app/src/main/java/pegasus/bluetootharduino/ManualActivity.java
```

* **What is the expected behavior?**

Replace the button-based control scheme with a joystick style control.

* **What is the motivation / use case for changing the behavior?**

Using a joystick-style control scheme would be much more intuitive, and would help with handling.

* **Please tell us about your environment:**
  
Current environment (version unknown)

* **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links eg. stackoverflow)

N/A

**Comment by DataQub3** [comment]
I agree that the manual control with ++ is not intuitive.  We could build a joystick-style GUI like you suggest, but that would take a fair effort.

The other option is to use the transmitter that came with the original car.  That would require extra wiring to switch between manual transmitter mode and autodrive (assuming the receiver in the car still works OK).  However I think it is a better solution because the transmitter is easier to use.

Neither option is easy though.  I will put it on the wishlist, but lower than other feature requests.  Note: the DonkeyCar used last year by senior students has this feature.  In manual mode you use the transmitter to drive around the track.  You record the manual drive and use that to train a deep learning automatic driver.  Then the car has learnt to drive itself from your training!  The DonkeyCar should be simpler than the Android-Car-duino.  I really want to get mine working ...

**Comment by ghost** [comment]
The only reason why I suggested building it directly into the app, is then, hypothetical, a user could simply download the apk to their device without the needing to find the transceiver. Speaking of which, I'll probably be filing a few more bug reports & feature requests, all of them, including this one, are mainly as long term goals. To see if we can get other students, yr 11 & 12, interested in this project. So don't feel any pressure to work on these straight away.

**Comment by DataQub3** [comment]
Good point.  I will investigate the joystick-style GUI further.

**Comment by DataQub3** [comment]
I added a virtual joystick to the application.  The library used is https://github.com/controlwear/virtual-joystick-android.  Code has been committed to github.

I have tested it only on a standalone phone.  Testing with the car is still required.   The sensitivity of the joystick is controlled by the "Advanced Settings" carMaxSpeed and carScaleSteering.
